defmodule Smb.SessionError do
  @errors [
    # SMB X/Open error codes for the ERRDOS error class
    errsuccess: 0,
    errbadfunc: 1,
    errbadfile: 2,
    errbadpath: 3,
    errnofids: 4,
    errnoaccess: 5,
    errbadfid: 6,
    errbadmcb: 7,
    errnomem: 8,
    errbadmem: 9,
    errbadenv: 10,
    errbadaccess: 12,
    errbaddata: 13,
    errres: 14,
    errbaddrive: 15,
    errremcd: 16,
    errdiffdevice: 17,
    errnofiles: 18,
    errgeneral: 31,
    errbadshare: 32,
    errlock: 33,
    errunsup: 50,
    errnetnamedel: 64,
    errnosuchshare: 67,
    errfilexists: 80,
    errinvalidparam: 87,
    errcannotopen: 110,
    errinsufficientbuffer: 122,
    errinvalidname: 123,
    errunknownlevel: 124,
    errnotlocked: 158,
    errrename: 183,
    errbadpipe: 230,
    errpipebusy: 231,
    errpipeclosing: 232,
    errnotconnected: 233,
    errmoredata: 234,
    errnomoreitems: 259,
    errbaddirectory: 267,
    erreasnotsupported: 282,
    errlogonfailure: 1326,
    errbuftoosmall: 2123,
    errunknownipc: 2142,
    errnosuchprintjob: 2151,
    errinvgroup: 2455,

    # here's a special one from observing NT
    errnoipc: 66,

    # These errors seem to be only returned by the NT printer driver system
    errdriveralreadyinstalled: 1795,
    errunknownprinterport: 1796,
    errunknownprinterdriver: 1797,
    errunknownprintprocessor: 1798,
    errinvalidseparatorfile: 1799,
    errinvalidjobpriority: 1800,
    errinvalidprintername: 1801,
    errprinteralreadyexists: 1802,
    errinvalidprintercommand: 1803,
    errinvaliddatatype: 1804,
    errinvalidenvironment: 1805,

    errunknownprintmonitor: 3000,
    errprinterdriverinuse: 3001,
    errspoolfilenotfound: 3002,
    errnostartdoc: 3003,
    errnoaddjob: 3004,
    errprintprocessoralreadyinstalled: 3005,
    errprintmonitoralreadyinstalled: 3006,
    errinvalidprintmonitor: 3007,
    errprintmonitorinuse: 3008,
    errprinterhasjobsqueued: 3009,

    # Error codes for the ERRSRV class

    errerror: 1,
    errbadpw: 2,
    errbadtype: 3,
    erraccess: 4,
    errinvnid: 5,
    errinvnetname: 6,
    errinvdevice: 7,
    errqfull: 49,
    errqtoobig: 50,
    errinvpfid: 52,
    errsmbcmd: 64,
    errsrverror: 65,
    errfilespecs: 67,
    errbadlink: 68,
    errbadpermits: 69,
    errbadpid: 70,
    errsetattrmode: 71,
    errpaused: 81,
    errmsgoff: 82,
    errnoroom: 83,
    errrmuns: 87,
    errtimeout: 88,
    errnoresource: 89,
    errtoomanyuids: 90,
    errbaduid: 91,
    errusempx: 250,
    errusestd: 251,
    errcontmpx: 252,
    errbadPW: nil,
    errnosupport: 0,
    errunknownsmb: 22,

    # Error codes for the ERRHRD class

    errnowrite: 19,
    errbadunit: 20,
    errnotready: 21,
    errbadcmd: 22,
    errdata: 23,
    errbadreq: 24,
    errseek: 25,
    errbadmedia: 26,
    errbadsector: 27,
    errnopaper: 28,
    errwrite: 29,
    errread: 30,
    errwrongdisk: 34,
    errfcbunavail: 35,
    errsharebufexc: 36,
    errdiskfull: 39,
  ]

  def error(atom) do
    @errors[atom]
  end

  def hard_msgs do
    %{
      error(:errnowrite) => "Attempt to write on write-protected diskette.",
      error(:errbadunit) => "Unknown unit.",

      error(:errnotready) => "Drive not ready.",
      error(:errbadcmd) => "Unknown command.",
      error(:errdata) => "Data error (CRC).",
      error(:errbadreq) => "Bad request structure length.",
      error(:errseek) => "Seek error.",
      error(:errbadmedia) => "Unknown media type.",
      error(:errbadsector) => "Sector not found.",
      error(:errnopaper) => "Printer out of paper.",
      error(:errwrite) => "Write fault.",
      error(:errread) => "Read fault.",
      error(:errgeneral) => "General failure.",
      error(:errbadshare) => "An open conflicts with an existing open.",
      error(:errlock) => "A Lock request conflicted with an existing lock or specified an invalid mode, or an Unlock requested attempted to remove a lock held by another process.",
      error(:errwrongdisk) => "The wrong disk was found in a drive.",
      error(:errfcbunavail) => "No FCBs are available to process request.",
      error(:errsharebufexc) => "A sharing buffer has been exceeded.",
    }
  end

end
